routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', ['uses' => 'SampleController@CalendarEvent']);

Route::resource('calendar_events', 'CalendarEventController');
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware'=>['auth']], function (){


/* Surat Masuk */
	Route::get('/admin', 'SuratMasukController@viewSuratMasuk');
	//index
    Route::get('/admin/suratmasuk', 'SuratMasukController@viewSuratMasuk');
	//create
	Route::get('/admin/suratmasuk/create', 'SuratMasukController@create');
    Route::post('/admin/suratmasuk/store', 'SuratMasukController@createSuratMasuk');
	//edit
	Route::get('/admin/suratmasuk/edit/{id}', 'SuratMasukController@edit');
    Route::post('/admin/suratmasuk/update/', 'SuratMasukController@updateSuratMasuk');
    //delete
    Route::get('/admin/suratmasuk/delete/{id}', 'SuratMasukController@deleteSuratMasuk');
    //search
    Route::get('/admin/suratmasuk/search', 'SuratMasukController@searchSuratMasuk');
	//rekap
	Route::get('/admin/suratmasuk/rekap', 'SuratMasukController@rekapitulasiSuratMasuk');
	//filter
    Route::get('/admin/suratmasuk/filter', 'SuratMasukController@filterSuratMasuk');

/* Surat Keluar */
    //index
    Route::get('/admin/suratkeluar', 'SuratKeluarController@viewSuratKeluar');
    //create
    Route::get('/admin/suratkeluar/create', 'SuratKeluarController@create');
    Route::post('/admin/suratkeluar/store', 'SuratKeluarController@createSuratKeluar');
    //edit
    Route::get('/admin/suratkeluar/edit/{id}', 'SuratKeluarController@edit');
    Route::post('/admin/suratkeluar/update/', 'SuratKeluarController@updateSuratKeluar');
    //delete
    Route::get('/admin/suratkeluar/delete/{id}', 'SuratKeluarController@deleteSuratKeluar');
    //search
    Route::get('/admin/suratkeluar/search', 'SuratKeluarController@searchSuratKeluar');
    //rekap
	Route::get('/admin/suratkeluar/rekap', 'SuratKeluarController@rekapitulasiSuratKeluar');
    //filter
    Route::get('/admin/suratkeluar/filter', 'SuratKeluarController@filterSuratKeluar');

/* Peminjaman Ruang */
    //index
    Route::get('/admin/peminjaman/{ruang}', 'PeminjamanController@viewPeminjaman');
    //create
    Route::get('/admin/peminjaman/{ruang}/create', 'PeminjamanController@create');
    Route::post('/admin/peminjaman/store', 'PeminjamanController@addPeminjaman');
    //edit
    Route::get('/admin/peminjaman/{ruang}/edit/{id}', 'PeminjamanController@edit');
    Route::post('/admin/peminjaman/update/', 'PeminjamanController@editPeminjaman');
    //delete
    Route::get('/admin/peminjaman/{ruang}/delete/{id}', 'PeminjamanController@cancelPeminjaman');
    //search
    Route::get('/admin/peminjaman/{ruang}/search', 'PeminjamanController@searchPeminjaman');
    //approve
    Route::get('/admin/peminjaman/{ruang}/approve/{id}', 'PeminjamanController@approvePeminjaman');
    //rekap
    Route::get('/admin/peminjaman/{ruang}/rekap', 'PeminjamanController@rekapitulasiPeminjaman');
	//filter
    Route::get('/admin/peminjaman/{ruang}/filter', 'PeminjamanController@filterPeminjaman');

});

app/CalendarEvent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use MaddHatter\LaravelFullcalendar\Event;
use MaddHatter\LaravelFullcalendar\Calendar;

class CalendarEvent extends Model implements \MaddHatter\LaravelFullcalendar\Event
{

    protected $dates = ['start', 'end'];

    /**
     * Get the event's title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Is it an all day event?
     *
     * @return bool
     */
    public function isAllDay()
    {
        return $this->is_all_day;
    }

    /**
     * Get the start time
     *
     * @return DateTime
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Get the end time
     *
     * @return DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * Get the event's ID
     *
     * @return int|string|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Optional FullCalendar.io settings for this event
     *
     * @return array
     */
    public function getEventOptions()
    {
        return [
            'color' => $this->background_color,
        ];
    }
}

app/Http/Controllers/CalendarEventController.php
<?php namespace App\Http\Controllers;

use App\CalendarEvent;
use App\Peminjaman;
use App\Http\Requests;
use App\Http\Requests\Calender\StoreRequest;
use App\Http\Requests\Calender\UpdateRequest;
use Illuminate\Http\Request;
use Redirect;
use \Input as Input;


class CalendarEventController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $calendar_events = CalendarEvent::all();

        return view('calendar_events.index', compact('calendar_events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('calendar_events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(StoreRequest $request)
    {
        $peminjamans = new Peminjaman();
        $peminjamans->namaRuang=$request->namaRuang;
        $peminjamans->tanggalPakai=$request->tanggalPakai;
        $peminjamans->kegiatan=$request->kegiatan;
        $peminjamans->namaPeminjam=$request->namaPeminjam;
        $peminjamans->kontak=$request->kontak;
        $peminjamans->jamMulai=$request->jamMulai;
        $peminjamans->jamSelesai=$request->jamSelesai;
		if($request->jamMulai>=$request->jamSelesai){
			return  redirect('/')->with('alert-success', 'Jam Mulai tidak dapat Lebih Besar dari Jam Selesai.')->with('tanggal', $peminjamans->tanggalPakai)->with('kegiatan', $peminjamans->kegiatan)->with('nama', $peminjamans->namaPeminjam)->with('kontak', $peminjamans->kontak)->with('mulai', $peminjamans->jamMulai)->with('selesai', $peminjamans->jamSelesai);
		}
		
        if(Input::hasFile('file')){
			$file= Input::file('file');
			$file->move('uploads',$file->getClientOriginalName());
            $peminjamans->lampiran = $file->getClientOriginalName();
		}
        $peminjamans->status=$request->status;
        $peminjamans->save();

        $calendar_event = new CalendarEvent();
        $calendar_event->peminjamanID     = $peminjamans->id;
        $calendar_event->title            = $request->kegiatan;
		$mulai							  = $request->tanggalPakai." ".$request->jamMulai.":00";
		$selesai						  = $request->tanggalPakai." ".$request->jamSelesai.":00";
        $calendar_event->start            = $mulai;
        $calendar_event->end              = $selesai;
        $calendar_event->is_all_day       = $request->input("is_all_day");
        if($request->namaRuang=='Ruang Sidang'){

			if($request->status=='Disetujui')
			{
				$calendar_event->background_color = '#B71C1C';
			}
			else
			{
				$calendar_event->background_color = '#EF9A9A';
			}
		}
		else{

			if($request->status=='Disetujui')
			{
				$calendar_event->background_color = ' #1B5E20';
			}
			else
			{
				$calendar_event->background_color = '#81C784';
			}
		}
        $calendar_event->save();

        return redirect('/')->with('message', 'Item created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $calendar_event = CalendarEvent::findOrFail($id);

        return view('calendar_events.show', compact('calendar_event'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $calendar_event = CalendarEvent::findOrFail($id);

        return view('calendar_events.edit', compact('calendar_event'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int    $id
     * @param Request $request
     * @return Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $calendar_event = CalendarEvent::findOrFail($id);

        $calendar_event->title            = $request->input("title");
        $calendar_event->start            = $request->input("start");
        $calendar_event->end              = $request->input("end");
        $calendar_event->is_all_day       = $request->input("is_all_day");
        $calendar_event->background_color = $request->input("background_color");

        $calendar_event->save();

        return redirect()->route('calendar_events.index')->with('message', 'Item updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $calendar_event = CalendarEvent::findOrFail($id);
        $calendar_event->delete();

        return redirect()->route('calendar_events.index')->with('message', 'Item deleted successfully.');
    }

}

resources/views/calendar_events/create.blade.php
@extends('layouts.cal')

@section('content')
    <div class="page-header">
        <h1>CalendarEvents / Create </h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('calendar_events.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group{{ $errors->has('namaRuang') ? ' has-error' : '' }}">
                    <label for="status">Ruang</label>
                    <input type="radio" name="namaRuang"  value="Ruang Sidang" onClick="document.getElementById('bg').value='#ff0000'"> Ruang Sidang<br>
                    <input type="radio" name="namaRuang"  value="Laboratorium" onClick="document.getElementById('bg').value='#0000ff'"> Laboratorium<br>
                    {!! $errors->first('namaRuang', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('tanggalPakai') ? ' has-error' : '' }}">
                    <label for="tanggalPakai">Tanggal Pemakaian</label>
                    <input type="date" name="tanggalPakai" class="form-control" placeholder="Tanggal Pemakaian" value="{{ old('tanggal') }}">
                    {!! $errors->first('tanggalPakai', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('kegiatan') ? ' has-error' : '' }}">
                    <label for="kegiatan">Kegiatan</label>
                    <input type="text" name="kegiatan" class="form-control" placeholder="Kegiatan" value="{{ old('penerima') }}">
                    {!! $errors->first('kegiatan', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('namaPeminjam') ? ' has-error' : '' }}">
                    <label for="namaPeminjam">Nama Peminjam</label>
                    <input type="text" name="namaPeminjam" class="form-control" placeholder="Nama Peminjam" value="{{ old('penerima') }}">
                    {!! $errors->first('namaPeminjam', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('kontak') ? ' has-error' : '' }}">
                    <label for="kontak">Kontak</label>
                    <input type="number" name="kontak" class="form-control" placeholder="Kontak" value="{{ old('penerima') }}">
                    {!! $errors->first('kontak', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('jamMulai') ? ' has-error' : '' }}">
                    <label for="jamMulai">Jam Mulai</label>
                    <input type="time" name="jamMulai" class="form-control" placeholder="Jam Mulai" value="{{ old('tanggal') }}" step="3600">
                    {!! $errors->first('jamMulai', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('jamSelesai') ? ' has-error' : '' }}">
                    <label for="jamSelesai">Jam Selesai</label>
                    <input type="time" name="jamSelesai" class="form-control" placeholder="Jam Selesai" value="{{ old('tanggal') }}" step="3600">
                    {!! $errors->first('jamSelesai', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group{{ $errors->has('lampiran') ? ' has-error' : '' }}">
                    <label for="upload">Lampiran</label>
                    <input type="file" name="file" id="file"></input>
                    {!! $errors->first('lampiran', '<p class="help-block">:message</p>') !!}
                </div>
                <input type="hidden" name="status" class="form-control" value="Dipesan"/>
                <input type="hidden" name="is_all_day" class="form-control" value="0"/>
                <input type="hidden" name="background_color" id="bg" class="form-control" value=""/>
            <a class="btn btn-default" href="{{ route('calendar_events.index') }}">Back</a>
            <button class="btn btn-primary" type="submit" >Create</button>
            </form>
        </div>
    </div>

@endsection

resources/views/calendar_events/edit.blade.php
@extends('layouts.cal')


@section('content')
    <div class="page-header">
        <h1>CalendarEvents / Edit </h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('calendar_events.update', $calendar_event->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static">{{$calendar_event->id}}</p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <input type="text" name="title" class="form-control" value="{{$calendar_event->title}}"/>
                </div>
                    <div class="form-group">
                     <label for="start">START</label>
                     <input type="text" name="start" class="form-control" value="{{$calendar_event->start}}"/>
                </div>
                    <div class="form-group">
                     <label for="end">END</label>
                     <input type="text" name="end" class="form-control" value="{{$calendar_event->end}}"/>
                </div>
                    <div class="form-group">
                     <label for="is_all_day">IS_ALL_DAY</label>
                     <input type="text" name="is_all_day" class="form-control" value="{{$calendar_event->is_all_day}}"/>
                </div>
                    <div class="form-group">
                     <label for="background_color">BACKGROUND_COLOR</label>
                     <input type="text" name="background_color" class="form-control" value="{{$calendar_event->background_color}}"/>
                </div>



            <a class="btn btn-default" href="{{ route('calendar_events.index') }}">Back</a>
            <button class="btn btn-primary" type="submit" >Save</button>
            </form>
        </div>
    </div>


@endsection

resources/views/calendar_events/index.blade.php
@extends('layouts.cal')


@section('content')
    <div class="page-header">
        <h1>CalendarEvents</h1>
    </div>


    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>TITLE</th>
                        <th>Jam Mulai</th>
                        <th>Jam Selesai</th>
                        <th>IS_ALL_DAY</th>
                        <th>BACKGROUND_COLOR</th>
                        <th class="text-right">OPTIONS</th>
                    </tr>
                </thead>

                <tbody>

                @foreach($calendar_events as $calendar_event)
                <tr>
                    <td>{{$calendar_event->id}}</td>
                    <td>{{$calendar_event->title}}</td>
                    <td>{{$calendar_event->start}}</td>
                    <td>{{$calendar_event->end}}</td>
                    <td>{{$calendar_event->is_all_day}}</td>
                    <td>{{$calendar_event->background_color}}</td>

                    <td class="text-right">
                        <a class="btn btn-primary" href="{{ route('calendar_events.show', $calendar_event->id) }}">View</a>
                        <a class="btn btn-warning " href="{{ route('calendar_events.edit', $calendar_event->id) }}">Edit</a>
                        <form action="{{ route('calendar_events.destroy', $calendar_event->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };"><input type="hidden" name="_method" value="DELETE"><input type="hidden" name="_token" value="{{ csrf_token() }}"> <button class="btn btn-danger" type="submit">Delete</button></form>
                    </td>
                </tr>

                @endforeach

                </tbody>
            </table>

            <a class="btn btn-success" href="{{ route('calendar_events.create') }}">Create</a>
        </div>
    </div>


@endsection

resources/views/calendar_events/show.blade.php
@extends('layouts.cal')


@section('content')
    <div class="page-header">
        <h1>CalendarEvents / Show </h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static">{{$calendar_event->id}}</p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$calendar_event->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="start">START</label>
                     <p class="form-control-static">{{$calendar_event->start}}</p>
                </div>
                    <div class="form-group">
                     <label for="end">END</label>
                     <p class="form-control-static">{{$calendar_event->end}}</p>
                </div>
                    <div class="form-group">
                     <label for="is_all_day">IS_ALL_DAY</label>
                     <p class="form-control-static">{{$calendar_event->is_all_day}}</p>
                </div>
                    <div class="form-group">
                     <label for="background_color">BACKGROUND_COLOR</label>
                     <p class="form-control-static">{{$calendar_event->background_color}}</p>
                </div>
            </form>



            <a class="btn btn-default" href="{{ route('calendar_events.index') }}">Back</a>
            <a class="btn btn-warning" href="{{ route('calendar_events.edit', $calendar_event->id) }}">Edit</a>
            <form action="#/$calendar_event->id" method="DELETE" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };"><button class="btn btn-danger" type="submit">Delete</button></form>
        </div>
    </div>


@endsection